### ISSUE TITLE
integration into existing virtual environment

### ISSUE THREAD

**Issue by ahnsv** [kaxil/airflowctl#18]
Hi, I'm a new user of this project. 
I wonder if this project intends to support usecase where users have existing virutal environment. 
FYI, I am trying to integrate this project as our local development environment. Since we already installed airflow package, it doesn't need to re-install airflow dependencies.

**Comment by kaxil** [comment]
That is definitely an intention to support existing environments, thanks for opening the GH issues.

I will tackle it in coming weeks but feel free to open a PR if you'd like to work on it
