### ISSUE TITLE
"source not found error" when  executing "airflowctl start command"

### ISSUE THREAD

**Issue by peterotool** [kaxil/airflowctl#3]
When i run the following command:

❯  airflowctl start 

I got this error:
Verifying Airflow installation...
/bin/sh: 1: source: not found
Error starting Airflow: Command 'source /home/peter/Desktop/Code/airflow/airflow_2.6.3/.venv/bin/activate && airflow version' returned non-zero exit status 127.

I installed pyenv and airflowctl on Ubuntu 20.04.6 LTS

Any clue about why  the "Verifying Airflow installation... process " use sh rather than bash?

Thanks in advance

**Comment by kaxil** [comment]
This is now fixed in 0.1.8: run `pip install -U airflowctl` :)

**Comment by kaxil** [comment]
Going to close it but please feel free to re-open it if the issue persists with the new version
