### ISSUE TITLE
`build` installs packages into the global user space when running from a venv

### ISSUE THREAD

**Issue by Dev-iL** [kaxil/airflowctl#30]
`airflowctl build` appears to install packages into the "root" (i.e. the non-venv) python environment, which causes dependency conflicts and ultimately fails to initialize the project properly. The **expected behavior** is to have the packages installed in the venv newly created by `airflowctl`. Below is the process I go through for setting up an airflowctl project:

1. Create a dedicated venv for running airflowctl (`"actl"`).
2. Activate `actl` and `pip install airflowctl`.
3. Use `airflowctl init ...` to initialize a new project.
4. Use `airflowctl build ...` to set the project up.

I'm using python 3.9 on CentOS.

**Comment by kaxil** [comment]
Can you provide the following, please?

1. Logs of running each command
2. Contents of `settings.yaml` file
3. Contents of `PROJECT_PATH/.airflowctl/config.yaml`

**Comment by Dev-iL** [comment]
As I was creating the requested outputs, I noticed I cannot reproduce the issue. Looks like it was a false alarm due to a human error on my end when setting it up earlier. Will reopen if I manage to reproduce this at a later time. Thank you for your time, and sorry for the confusion!

BTW,
Is airflowctl supposed to automatically install the dependencies from `requirements.txt` or should the user manually `pip install -r ...` after building the project?

**Comment by kaxil** [comment]
@Dev-iL Glad to hear that. Yes, `airflowctl build` command will install all deps from `requirements.txt`. I can make the docs in https://github.com/kaxil/airflowctl?tab=readme-ov-file#step-2-build-the-project even more clearer if you think that would help

**Comment by Dev-iL** [comment]
@kaxil Yes, I think it would be good to say explicitly that all the files mentioned in step 1 (and not just `settings.yaml`) should be edited before running `build`.

BTW, I asked because I don't recall the requirements auto-installing for me in the past. I only had one dependency (specified as a git link), which is a package configured using `pyproject.toml`. Is it possible that the venv created by airflowctl does so w/o ensuring `pip` is up-tp-date (as of python>=3.9 this can be done using the `--upgrade-deps` flag), and as a result airflowctl uses some arbitrary `pip` version that's potentially incompatible with `pyproject.toml` and skips installing some/all dependencies?
