### ISSUE TITLE
Remove pip as the primary installation method

### ISSUE THREAD

**Issue by ketozhang** [kaxil/airflowctl#33]
airflowctl is affected by the chicken-and-egg problem of Python version. No surprisingly it has the same burden as other Python environment & project managers (e.g., `hatch`, `pipx`, `pyenv`) :

If we start with `pip`, the version used in airflowctl built must match the same version as your pip environment:
  ```console
    $ python -V
    Python X.Y.Z

    $ python -m pip install airflowctl
    $ airflowctl init --python-version=X.Y.Z .
    $ airflowctl build .
  ```

Otherwise `pyenv` is invoked to get the correct python version (forcing users to use a specific version manager).

The above is the ideal instruction if we're going to use `pip`. With the current instructions, you can run into a lot of issues if you have one of these situation:

- `--python-version` is not the same as the version used in `pip install airflowctl`
- `--python-version` is not specified
- `pyenv` is not available
- `python` is a different version than the one installed with `pip`. For example:
  - In a broken environment where `python` and `pip` are related
  - User later on upgraded Python and did not reinstall `airflowctl`.

Here are my suggestions:
- Installation instructions should remove `pip` as the primary method.
- Ideally, `airflowctl` behaviors should not depend on the Python version it is installed to. 
- `airflowctl build` should fail if `python_version` does not exist in `$PATH`. Error message should ask users to have the correct Python version.
  - Alternatively, users can override which Python path to build the virtual environment with.
- Provide a Python-agnostic installation method (e.g., `brew`, `apt`, `yum`, `winget`, `choco`, etc.)

Alternatively, although a bigger rewrite, switch to using `hatch` or `rye`.

**Comment by kaxil** [comment]
I have switched to using `uv` (PR: https://github.com/kaxil/airflowctl/pull/39) and created [0.2.11](https://github.com/kaxil/airflowctl/releases/tag/0.2.11). Let me know if you try it out

**Comment by ketozhang** [comment]
```console
$ uv tool install airflowctl
$  airflowctl init my_airflow_project --build-start
$ ls -la my_airflow_project
total 1416
drwxr-xr-x  15 keto  staff     480 Nov 18 10:28 .
drwx------   3 keto  staff      96 Nov 18 10:27 ..
drwxr-xr-x   3 keto  staff      96 Nov 18 10:27 .airflowctl
-rw-r--r--   1 keto  staff     316 Nov 18 10:27 .env
-rw-r--r--   1 keto  staff     150 Nov 18 10:27 .gitignore
drwxr-xr-x   9 keto  staff     288 Nov 18 10:27 .venv
-rw-------   1 keto  staff   87628 Nov 18 10:27 airflow.cfg
-rw-r--r--   1 keto  staff  581632 Nov 18 10:28 airflow.db
drwxr-xr-x   4 keto  staff     128 Nov 18 10:28 dags
drwxr-xr-x   4 keto  staff     128 Nov 18 10:28 logs
drwxr-xr-x   2 keto  staff      64 Nov 18 10:27 plugins
-rw-r--r--   1 keto  staff       0 Nov 18 10:27 requirements.txt
-rw-r--r--   1 keto  staff     717 Nov 18 10:27 settings.yaml
-rw-------   1 keto  staff      16 Nov 18 10:27 standalone_admin_password.txt
-rw-r--r--   1 keto  staff    4762 Nov 18 10:28 webserver_config.py
```

That's much better. Thank you!
